<?php 
    $show = $this->helper('Aplazo\AplazoPayment\Helper\Data')->getConfig('payment/aplazo_payment/show_on_cart');
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $cart = $objectManager->get('\Magento\Checkout\Model\Cart');
    $price = $cart->getQuote()->getGrandTotal() * 100;

    if($show == 1){
?> 
        <aplazo-placement product-price = <?php echo $price; ?>></aplazo-placement>
<?php
    }
?>