<?php
/**
 * \Aplazo\AplazoPayment\Block\Checkoutjs $block
 */
?>
<script type="text/javascript">

var aplazoSubtitle = '<?php echo $block->getSubtitle(); ?>';
require([
    'mage/url'
], function (url) {
    window.Aplazo = new Function();
    function _findElementById(elementId) {
        return document.getElementById(elementId);
    }
    function _showLoader() {
        const [_body] = document.getElementsByName('body');
        _body.dispatchEvent(new Event("processStart"));
    }
    function _hideLoader() {
        const [_body] = document.getElementsByName('body');
        _body.dispatchEvent(new Event("processStop"));
    }
    Aplazo.prototype = {
        initialize: function () {
            this.buyWithAplazoId = '#buy_with_aplazo_checkout';
            this.buyWithAplazoSelector = _findElementById(this.buyWithAplazoId);
            this.aplazoPaymentAjaxUrl = '<?= $block->escapeHtml($block->getBaseUrl()); ?>aplazopayment/index/transaction';
            this.aplazoErrorClass = '.error-aplazopayment';
            this.initEvents();
        },
        initEvents: function () {
            var that = this;
            _findElementById(document).addEventListener("click", this.buyWithAplazoId, function () {
                that.buyWithAplazoEventClick(that);
            });
        },
        buyWithAplazoEventClick: function (_this) {
            _showLoader();
            fetch(_this.aplazoPaymentAjaxUrl)
                .then(response => {
                    localStorage.removeItem('mage-cache-storage');
                    _hideLoader();
                    if (response.error === false && response.redirecturl !== null) {
                        let url = response.redirecturl;
                        window.location = url;
                    } else {
                        console.log(response);
                    }
                }).catch(error => {
                _hideLoader();
                console.log(error);
            });
        }
    };
    var aplazo = new Aplazo();
    aplazo.initialize();
    window.aplazo = aplazo;
});

</script>
