<?php
/**
 * \Aplazo\AplazoPayment\Block\Checkoutjs $block
 */
?>
<script src="https://cdn.aplazo.mx/aplazo-widgets.min.js"></script>
<script type="text/javascript">

var aplazoSubtitle = '<?php echo $block->getSubtitle(); ?>';
require([
    'mage/url'
], function (url) {
    window.Aplazo = new Function();
    function _findElementById(elementId) {
        return document.getElementById(elementId);
    }
    function _showLoader() {
        const [_body] = document.getElementsByName('body');
        _body.dispatchEvent(new Event("processStart"));
    }
    function _hideLoader() {
        const [_body] = document.getElementsByName('body');
        _body.dispatchEvent(new Event("processStop"));
    }
    Aplazo.prototype = {
        initialize: function () {
            this.aplazoPaymentAjaxUrl = '<?= $block->escapeHtml($block->getBaseUrl()); ?>aplazopayment/index/transaction';
            this.aplazoErrorClass = '.error-aplazopayment';
        },
    };
    var aplazo = new Aplazo();
    aplazo.initialize();
    window.aplazo = aplazo;
});

</script>