<?php

/**
 * @var \Aplazo\AplazoPayment\Block\Successpage $block
 */
?>
<script>
    require([
        'Magento_Customer/js/customer-data'
    ], function (customerData) {
        var sections = ['cart'];
        customerData.invalidate(sections);
        customerData.reload(sections, true);
    });
</script>
<div class="checkout-success">
    <h1><?= $block->escapeHtml(__('Thank you for your purchase!')) ?></h1>
    <h2><?= $block->escapeHtml(__('Your order has been placed and will be processed as soon as posible.')) ?></h2>
    <?php //if ($block->getOrderId()) :?>
            <p><?= $block->escapeHtml(__('Your order # is: ')) ?><b><?php echo str_replace ( '/', '', $block->getIncrementId()); ?></b></p>
            <p><?= $block->escapeHtml(__('We\'ll email you an order confirmation with details and tracking info.')) ?></p>
    <?php //endif;?>

    <?= $block->getAdditionalInfoHtml() ?>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?= $block->escapeUrl($block->getBaseUrl()) ?>"><span><?= $block->escapeHtml(__('Continue Shopping')) ?></span></a>
        </div>
    </div>
</div>